name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build with
        run: mvn clean install -DskipTests=true

      - name: Run tests
        run: mvn test

